### ISSUE TITLE
Create flim view with facets for type and genre

### ISSUE THREAD

**Issue by copelco** [caktus/django-filters-facet#4]
Model view after Traffic Stops view

- [x] Show paginated list of films on `/films/`
    - [x] Add view to `films/views.py` (using firearms or traffic stops as reference) 
    - [x] Add template to `flims/templates/films/film_list.html` (using firearms or traffic stops as reference) 
    - [x] Add url to `films/urls.py`
    - [x] Import films urls module in `example_project/urls.py`
- [x] Add `FlimFilterSet` 
- [x] When you click on Movies in navigation, user sees list of movies with filterable facets

**Comment by jcjudkins** [comment]
#11 completed

**Comment by Jworthancaktus** [comment]
This can be closed.
